@baseUrl = http://localhost:3333
# @baseUrl = https://a59e-201-216-102-20.ngrok-free.app

@authToken = {{authenticate.response.body.access_token}}
@order_id = {{order.response.body.id}}
@payment_id_by_credit_card = {{set_credit_card.response.body.id}}
@payment_id_by_pix = {{generate_pix_code.response.body.id}}

# @name create_account
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Administrador DE VERDADE 2",
  "cpf": "00721223079",
  "email": "admin2@email.com",
  "password": "Pa$$word",
  "role": "ADMIN"  
}

### 
# @name authenticate
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "john.doe@email.com",
  "password": "Pa$$word"  
}

###

# @name create_food
POST {{baseUrl}}/foods
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Salada de Guacamole",
  "portion": 130,
  "calories": 445,
  "imageUrl": "https://images.unsplash.com/photo-1484980972926-edee96e0960d?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
}

###

# @name list_foods
GET {{baseUrl}}/foods?page=2
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_meal
POST {{baseUrl}}/meal
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "meal_date": "2024-06-19",
  "shift": "LUNCH",
  "price": 14.49,
  "availability": 150,
  "foods": [
    {
      "name": "Salada de Guacamole",
      "portion": 130,
      "calories": 445,
      "imageUrl": "https://images.unsplash.com/photo-1484980972926-edee96e0960d?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
      "id": 16,
      "createdAt": "2024-06-17T00:01:51.000Z",
      "updatedAt": "2024-06-17T00:01:51.000Z"
    }
  ]
}

###

# @name get_meals_of_the_day
GET {{baseUrl}}/meal?order_by=meal_date
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name order
POST {{baseUrl}}/orders
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "meal":  {
    "id": 8
  }
}

###

# @name set_payment_method_credit_card
PATCH {{baseUrl}}/orders/25/payment
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "payment_method": "CREDIT_CARD"
}

###

# @name set_payment_method_pix
PATCH {{baseUrl}}/orders/{{order_id}}/payment
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "payment_method": "PIX"
}

###

# @name set_credit_card
POST {{baseUrl}}/payment/credit-card
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "order": {
    "id": 25
  },
  "card_number": "4958754160219305",
  "expiration_date": "2026-05-12",
  "security_code": 448,
  "account_holder": "MOISES S AZEVEDO"
}

###

# @name generate_pix_code
POST {{baseUrl}}/payment/pix
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "order": {
    "id": {{order_id}}
  }
}

###

# @name process_payment_by_credit_card
PATCH {{baseUrl}}/payment/20/process
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name process_payment_by_pix
PATCH {{baseUrl}}/payment/{{payment_id_by_pix}}/process
Content-Type: application/json
Authorization: Bearer {{authToken}}
###

# @name validate_voucher
PATCH {{baseUrl}}/voucher/10/validate
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name list_vouchers
GET {{baseUrl}}/voucher?user_id=4&order_by=createdAt&order_by_direction=DESC
Content-Type: application/json
Authorization: Bearer {{authToken}}


###

# @name post_feedback
POST {{baseUrl}}/feedback/10
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "content": "Estava muito bom."
}

###

# @name list_meal_feedbacks
GET {{baseUrl}}/feedback/8?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name report_vouchers
GET {{baseUrl}}/voucher/report/by-date?date=2024-06-25
Content-Type: application/json
Authorization: Bearer {{authToken}}



