@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}
@order_id = {{order.response.body.id}}
@payment_id_by_credit_card = {{set_credit_card.response.body.id}}
@payment_id_by_pix = {{generate_pix_code.response.body.id}}

# @name create_account
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Administrador DE VERDADE 2",
  "cpf": "00721223079",
  "email": "admin2@email.com",
  "password": "Pa$$word",
  "role": "ADMIN"  
}

### 
# @name authenticate
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "john.doe@email.com",
  "password": "Pa$$word"  
}

###

# @name create_food
POST {{baseUrl}}/foods
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Carne de Panela",
  "portion": 130,
  "calories": 347,
  "imageUrl": "https://unsplash.com/pt-br/fotografias/salada-top-view-com-guacamole-oaz0raysASk"
}

###

# @name list_foods
GET {{baseUrl}}/foods?page=2
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name create_meal
POST {{baseUrl}}/meal
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "meal_date": "2024-05-30",
  "shift": "LUNCH",
  "price": 14.49,
  "availability": 150,
  "foods": [
           {
      "id": 11,
      "createdAt": "2024-05-30T13:43:33.000Z",
      "updatedAt": "2024-05-30T13:43:33.000Z",
      "name": "Arroz Branco",
      "portion": 100,
      "calories": 130,
      "imageUrl": "https://unsplash.com/pt-br/fotografias/salada-top-view-com-guacamole-oaz0raysASk"
    },
    {
      "id": 12,
      "createdAt": "2024-05-30T13:44:05.000Z",
      "updatedAt": "2024-05-30T13:44:05.000Z",
      "name": "Feijão Carioca",
      "portion": 80,
      "calories": 347,
      "imageUrl": "https://unsplash.com/pt-br/fotografias/salada-top-view-com-guacamole-oaz0raysASk"
    },
    {
      "id": 13,
      "createdAt": "2024-05-30T13:44:47.000Z",
      "updatedAt": "2024-05-30T13:44:47.000Z",
      "name": "Salada de alface, tomate e rúcula",
      "portion": 60,
      "calories": 34,
      "imageUrl": "https://unsplash.com/pt-br/fotografias/salada-top-view-com-guacamole-oaz0raysASk"
    },
    {
      "id": 14,
      "createdAt": "2024-05-30T13:45:23.000Z",
      "updatedAt": "2024-05-30T13:45:23.000Z",
      "name": "Mandioca",
      "portion": 80,
      "calories": 138,
      "imageUrl": "https://unsplash.com/pt-br/fotografias/salada-top-view-com-guacamole-oaz0raysASk"
    },
    {
      "id": 15,
      "createdAt": "2024-05-30T13:45:48.000Z",
      "updatedAt": "2024-05-30T13:45:48.000Z",
      "name": "Carne de Panela",
      "portion": 130,
      "calories": 347,
      "imageUrl": "https://unsplash.com/pt-br/fotografias/salada-top-view-com-guacamole-oaz0raysASk"
    }
  ]
}

###

# @name get_meals_of_the_day
GET {{baseUrl}}/meal?date=2024-05-30
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name order
POST {{baseUrl}}/orders
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "meal":  {
    "id": 8
  }
}

###

# @name set_payment_method_credit_card
PATCH {{baseUrl}}/orders/25/payment
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "payment_method": "CREDIT_CARD"
}

###

# @name set_payment_method_pix
PATCH {{baseUrl}}/orders/{{order_id}}/payment
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "payment_method": "PIX"
}

###

# @name set_credit_card
POST {{baseUrl}}/payment/credit-card
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "order": {
    "id": 25
  },
  "card_number": "4958754160219305",
  "expiration_date": "2026-05-12",
  "security_code": 448,
  "account_holder": "MOISES S AZEVEDO"
}

###

# @name generate_pix_code
POST {{baseUrl}}/payment/pix
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "order": {
    "id": {{order_id}}
  }
}

###

# @name process_payment_by_credit_card
PATCH {{baseUrl}}/payment/20/process
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name process_payment_by_pix
PATCH {{baseUrl}}/payment/{{payment_id_by_pix}}/process
Content-Type: application/json
Authorization: Bearer {{authToken}}
###

# @name validate_voucher
PATCH {{baseUrl}}/voucher/10/validate
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name list_vouchers
GET {{baseUrl}}/voucher?user_id=1&order_by=createdAt
Content-Type: application/json
Authorization: Bearer {{authToken}}


###

# @name post_feedback
POST {{baseUrl}}/feedback/10
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "content": "Estava muito bom."
}

###

# @name list_meal_feedbacks
GET {{baseUrl}}/feedback/8?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}
